baseurl = "https://timemachineforpeace.blairmunroakusa.wp.computer/"
title = "Time Machine For Peace (Blair's 2021 attempt)."
author = "Blair Munro"
canonifyurls = true
languagecode = "en"

theme = "hugo-tanka"
themesDir = "themes"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "time machine for peace (Blair's failed 2021 kickoff attempt)"
  faviconfile = "images/UPC.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

